version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_qayim_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jeffxddowdowdow1234
      MYSQL_DATABASE: qayyim_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pJeffxddowdowdow1234"]
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_qayim_dev
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Jeffxddowdowdow1234
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  app-dev:
    image: node:18-alpine
    container_name: nextjs_app_qayim_dev
    working_dir: /app
    # Change: Only run npm install if node_modules is missing to save time
    command: >
      sh -c "if [ ! -d 'node_modules' ]; then npm install; fi && 
             npx prisma generate && 
             npm run dev -- -p 9002" 
    ports:
      - "9002:9002"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      DATABASE_URL: "mysql://root:Jeffxddowdowdow1234@mysql:3306/qayyim_db"
      NODE_ENV: development
      RESEND_API: ${RESEND_API}
      JWT_SECRET: ${JWT_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data_dev: